export { default as LoginTemplate } from './Login'
export { default as AuthTemplate } from './Auth'
export { default as ListTemplate } from './List'
export { default as CreateTemplate } from './Create'
export { default as ReleaseTemplate } from './Release'
export { default as ListOrderTemplate } from './ListOrder'
export { default as DetailsTemplate } from './ListDetails'
export { Main } from './Main'
