export { TableHeader } from './TableHeader'
export { Popover } from './Popover'
export { HeaderSettings } from './HeaderSettings'
export * from './Paginate'
export * from './SideBar/constants'

export type { HeaderProps } from './TableHeader'
export type { IHandleModalPropsEdit } from './Modais/Edit'
export type { IHandleModalColorsPropsNew } from './Modais/EditorStatus'
export type { IPermissions } from './SideBar/types'
